### ISSUE TITLE
[BUG] documented docker-compose.yml in official guides doesn't work

### ISSUE THREAD

**Issue by dzeroc** [opensearch-project/opensearch-devops#109]
Hi,

I'm experiencing that documented docker-compose.yml in official guides doesn't work.

Environment:
OS - Ubuntu 22.04 LTS
Docker Engine - Community - Version:  20.10.15
Docker Compose version v2.5.0

$ cat /proc/sys/vm/max_map_count
262144

I followed [this](https://opensearch.org/downloads.html) and then [this](https://opensearch.org/docs/latest/opensearch/install/docker/#start-a-cluster).

Running "docker-compose up" with https://opensearch.org/samples/docker-compose.yml it always returns:
```
opensearch-node1       | [2022-05-11T15:09:35,744][WARN ][o.o.c.c.ClusterFormationFailureHelper] [opensearch-node1] master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [opensearch-node1, opensearch-node2] to bootstrap a cluster: have discovered [{opensearch-node1}{HAXYh2n_TnSM-FiYgnZQDA}{sCEi7BXzSjy9AVRmUbfM5A}{172.24.0.4}{172.24.0.4:9300}{dimr}{shard_indexing_pressure_enabled=true}]; discovery will continue using [172.24.0.3:9300] from hosts providers and [{opensearch-node1}{HAXYh2n_TnSM-FiYgnZQDA}{sCEi7BXzSjy9AVRmUbfM5A}{172.24.0.4}{172.24.0.4:9300}{dimr}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
opensearch-node2       | [2022-05-11T15:09:45,308][WARN ][o.o.c.c.ClusterFormationFailureHelper] [opensearch-node2] master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [opensearch-node1, opensearch-node2] to bootstrap a cluster: have discovered [{opensearch-node2}{n6ZaxN9zRtir4noIuiPkMg}{_2Q8WoCLSd2gEiC1dPRkLw}{172.24.0.3}{172.24.0.3:9300}{dimr}{shard_indexing_pressure_enabled=true}]; discovery will continue using [172.24.0.4:9300] from hosts providers and [{opensearch-node2}{n6ZaxN9zRtir4noIuiPkMg}{_2Q8WoCLSd2gEiC1dPRkLw}{172.24.0.3}{172.24.0.3:9300}{dimr}{shard_indexing_pressure_enabled=true}] from last-known cluster state; node term 0, last-accepted version 0 in term 0

```

I changed docker image tag from latest to 1.3.2 and 1.3.0 with same results. 
Have i missed something?
Thanks in advance

**Comment by dblock** [comment]
I moved this into devops.

**Comment by jordarlu** [comment]
Hello, @jhill-cmd , I woud like to follow up on this case with you if you are still experiencing the issue? 

The 'latest' version of OpenSearch image at the moment is v2.5.0 (https://hub.docker.com/r/opensearchproject/opensearch/tags?page=1&name=2.5.0 and https://hub.docker.com/r/opensearchproject/opensearch/tags?page=1&name=latest), would you please share the docker-compose logs that we can have a look as well? Please also check what @tlfeng mentioned above (on May 30, 2022) if that helps.. 

Thanks!

**Comment by jordarlu** [comment]
Hi, @jhill-cmd and @dzeroc, please be aware a bit difference at the `enviroment` key config in the docker-compose.yml between OpsenSearch Build 1.x v.s. 2.x

for build 1.x : `- cluster.initial_master_nodes=opensearch-node1,opensearch-node2`
for build 2.x and above : `- cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2`

hope this rssolve your issue..
thanks,

**Comment by jordarlu** [comment]
Pls also refer to https://github.com/opensearch-project/opensearch-build/tree/main/docker/release/dockercomposefiles for docker-compose.yml reference per 1.x and 2.x(and above).  Thanks !!

**Comment by jordarlu** [comment]
Hi, @jhill-cmd and @dzeroc, I am closing this ticket for now, and pls feel free to re-open or create a new issue if you are facing the problem again, thanks!
