### ISSUE TITLE
Extract helm chart(s) into its own repo

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-devops#11]
Coming from https://github.com/opensearch-project/opensearch-devops/pull/4#issuecomment-885189466, should be its own project.

**Comment by dblock** [comment]
@TheAlgo since you PR-ed #4 if you have any interest in making/extracting this into a new repo I can help move it into the org

**Comment by davidkarlsen** [comment]
It can still reside here. What would be great is to publish the charts and index to a *helm repo* for instance using github pages and this gh action :https://github.com/helm/chart-release-action
Which makes consumption a lot easier

**Comment by dblock** [comment]
> It can still reside here. What would be great is to publish the charts and index to a _helm repo_ for instance using github pages and this gh action :https://github.com/helm/chart-release-action
> Which makes consumption a lot easier

What are the advantages to bundling all this in one repo? Feels like it's easy to make a mess. Each helm chart would have its own setup to be published every time code changes via CI that anyone can setup/contribute to as well.

**Comment by peterzhuamazon** [comment]
Instead of doing a new repo can we do something like this:
https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/693

**Comment by dblock** [comment]
> Instead of doing a new repo can we do something like this:
> [opendistro-for-elasticsearch/opendistro-build#693](https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/693)

Probably. My only worry is that this repo becomes a kitchen sink of all thinks devops that are unrelated to each-other. Will leave it to the people contributing to consider the pros and cons.

**Comment by dblock** [comment]
> This is a place for us to have multiple community projects co-exist and I would like to keep that behavior for now.

👍

**Comment by TheAlgo** [comment]
> Instead of doing a new repo can we do something like this:
> [opendistro-for-elasticsearch/opendistro-build#693](https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/693)
> 
> This is a place for us to have multiple community projects co-exist and I would like to keep that behavior for now.

@dblock @peterzhuamazon  @davidkarlsen  I will agree with Peter and David , if we can have an index that will make consumption easier.

**Comment by peterzhuamazon** [comment]
Both #4 and #10 are now in the repo, approved and merged.
Thanks everyone for the help in the process.
