### ISSUE TITLE
How to change base OS for OpenSearch container

### ISSUE THREAD

**Issue by swapnilsvaidya** [opensearch-project/opensearch-devops#117]
**Is your feature request related to a problem? Please describe.**
I want to know if there is a way to change the base OS used for building OpenSearch container image.
**Describe the solution you'd like**
I want to use ubuntu as base OS for running my OpenSearch container

**Describe alternatives you've considered**

**Additional context**

**Comment by Divyaasm** [comment]
This is where you need to update thye base image https://github.com/opensearch-project/opensearch-build/tree/main/docker/release/dockerfiles to build Docker image 
And the instructions to build the docker image are as follows https://github.com/opensearch-project/opensearch-build/tree/main/docker/release

**Comment by gaiksaya** [comment]
Closing this issue as it is answered. Please re-open if you have more questions.
Thanks!
