### ISSUE TITLE
[BUG] Not possible to set custom opensearch.yml using docker compose 

### ISSUE THREAD

**Issue by demianchuk** [opensearch-project/opensearch-devops#122]
**Describe the bug**
It is not possible to set custom opensearch.yml using docker compose 

**To Reproduce**
**1. Prepare next docker compose file:**
version: '3'

services:
  single_opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      -  discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    container_name: "single_opensearch_sergii2"
    volumes:
      - ./ci/opensearch/jvm.options:/usr/share/opensearch/config/jvm.options
      # Option A - for testing that parameters are mounted properly
      - ./ci/opensearch/custom-opensearch.yml:/usr/share/opensearch/config/custom-opensearch.yml
      # Option B - when parameters are mounted - then there is an error
      #- ./ci/opensearch/custom-opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - "9200:9200"
      - "9600:9600"
    expose:
      - "9200"

Note: custom-opensearch.yml content is taken while being inside opensearch container

2. Run docker-compose up -d using option A (look at docker compose file above, B option is commented) - opensearch container works normally, custom-opensearch.yml is mounted properly, content and permissions are correct (the same as opensearch.yml)

3. Comment option A at docker compose and uncomment option B. Docker container exits with error
"Caused by: org.opensearch.OpenSearchException: Unable to read /usr/share/opensearch/config/esnode.pem (/usr/share/opensearch/config/esnode.pem). Please make sure this files exists and is readable regarding to permissions. Property: plugins.security.ssl.transport.pemcert_filepath"
 

**Expected behavior**
Container should be running with overwritten configuration as it is described at official documentation
https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/

**Comment by jordarlu** [comment]
Thanks for the issue ,, let me check and comment.. thanks

**Comment by jordarlu** [comment]
Hi, @demianchuk , sorry for being late response on this issue..

**Comment by demianchuk** [comment]
Hi, @jordarlu 

Yes, I confirm all you wrote above

**Comment by jordarlu** [comment]
Thanks for confirming that, @demianchuk , in this case, can you try with different target filename in Option B? 

for example : using  `custom-opensearch.yml`. instead of `opensearch.yml `
```
# Option B - when parameters are mounted - then there is an error
#- ./ci/opensearch/custom-opensearch.yml:/usr/share/opensearch/config/custom-opensearch.yml
```

**Comment by jordarlu** [comment]
Hello again, @demianchuk ,, since it has been a while that we did not hear from you, I am going to close this issue with hoping that you were able to get the cluster up successfully ,, if not , please feel free to re-open this issue and we would love to dig it further with your input,  thanks !!
