### ISSUE TITLE
Create a "nightly" instance of Playground that gets updated everyday with the daily build.

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/opensearch-devops#129]
### Is your feature request related to a problem? Please describe

I'd like to be able to play with new features faster as they're getting build on OpenSearch.  Therefore, I'd like a "nightly" version of playground to get built with every successful build -- first with the 2.x build, but ultimately with main as well. 

### Describe the solution you'd like

Whenever there's a successful night built, we replace the current nightly playground build automatically.   We will need a way to see what version we're pointing at. 

### Acceptance Criteria:

1. Support upcoming version for 2.x
2. OS and OSD gets deployed nightly on a regular basis using the latest builds.
3. Have generic anonymous(read-only) access for OpenSearch DashBoards.
4. Display the commits related to a build-id.
5. The instance should be publicly accessible.

### Action Items
- [x] https://github.com/opensearch-project/opensearch-devops/issues/130
- [x] https://github.com/opensearch-project/opensearch-cluster-cdk/issues/72
- [x] https://github.com/opensearch-project/opensearch-cluster-cdk/issues/73
- [x] https://github.com/opensearch-project/opensearch-cluster-cdk/issues/74
- [x] https://github.com/opensearch-project/opensearch-cluster-cdk/issues/75 : Research and integrate opensearch-cluster-cdk into nightly playgrounds. May involve publishing the cdk code base to npm or consume it by cloning the repo. 
- [x] https://github.com/opensearch-project/opensearch-devops/issues/131
- [x] https://github.com/opensearch-project/opensearch-devops/issues/132
- [x] Set up accounts and required permissions (OIDC) to deploy the stacks on the infrastructure
- [x] Ensure the deploying artifact validation always validates with security plugin strictly
- [x] Add GHA deployment workflow for tools and notification stack
- [x] Add GHA deployment workflow for opensearch-cluster-cdk stacks to deploy nightly.

**Comment by gaiksaya** [comment]
Please see the high level design posted here: https://github.com/opensearch-project/opensearch-devops/issues/130
Thanks! Will be modifying the description of this issue into smaller issues. 
Thanks!

**Comment by gaiksaya** [comment]
Closing this issue as nightly playgrounds have been successfully working for last 2-3 releases https://playground.nightly.opensearch.org/
There are upcoming enhancements such as #153 which will be followed up in mentioned issue.
