### ISSUE TITLE
[Enhancement][Nightly Playground] Add Tools stack along with child components

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-devops#131]
**Is your feature request related to a problem? Please describe.**
Tools stack usually would contain a storage location for data, ways to index/delete data.

**Describe the solution you'd like**
![image](https://github.com/opensearch-project/opensearch-devops/assets/61760125/70e8aad6-a8ed-4817-a63b-86f2a5b1a20d)

**Describe alternatives you've considered**
Use curl 

**Acceptance Criteria**
* Any data set that is indexed in the cluster should be reviewed
* The stack should be able to accommodate indexing the data as per the user needs such as alias, etc.

**Comment by prudhvigodithi** [comment]
[Untriage]
@gaiksaya can you please add more acceptance criteria?
Thank you

**Comment by gaiksaya** [comment]
Synced up with @prudhvigodithi on this, we will first try the alternative approach:
1. PR the data required to be indexed in this repository under nightly-playrounds/data
2. Create a GHA workflow that would index the data upon merge or manual trigger
