### ISSUE TITLE
[Help Needed] OpenSearch/Dashboards in Ansible

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-devops#14]
[Help Needed] OpenSearch/Dashboards in Ansible.
We invite communities to help us adding more distros of OpenSearch/Dashboards.
We recently have Helm OpenSearch available with the help of community, and we would love more community contributions.

**Comment by DandyDeveloper** [comment]
@peterzhuamazon Can you better explain what this issue entails?

Do we want a playbook or a module that automatically deploys OpenSearch via Ansible? 

I think if contribution is expected, we should be able to clearly define expectations to someone wanting to contribute.

**Comment by peterzhuamazon** [comment]
Hi @DandyDeveloper I think we are looking to have a playbook to deploy OpenSearch/Dashboards.
There are expectations from community to playbook since ODFE and there is a community maintained one: https://github.com/saravanan30erd/opendistro_standalone_installation

Would love to see this also present in OpenSearch/Dashboards.

@saravanan30erd since you have worked on ODFE version and still maintain it, would you mind also take part in the discussion and evaluate the possibility of this?

Thanks.

**Comment by saravanan30erd** [comment]
@peterzhuamazon Sure, I can create ansible playbooks for OpenSearch & Dashboards installation. This [one](https://github.com/saravanan30erd/opendistro_standalone_installation) is created for Centos & RHEL, so I can create playbooks for Centos & RHEL initially and we can eventually support all other distributions(Ubuntu, etc,..).

Is it possible to create separate repo (opensearch-ansible or something) as I expect it might get big and complex going forward?

**Comment by peterzhuamazon** [comment]
Thanks @saravanan30erd for the responses, here are a few points to add on:
1. CentOS/RHEL is good as officially our releases on docker are based on AL2 which is in the same RH family.
2. The separate repo has been mentioned multiple times in the past weeks by community, and we are currently discussing about it. As of now, please just create a separate folder for it in opensearch-devops repo.

Please let me know if you have any questions.

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @saravanan30erd It has been some days since we last talk.
Just want to check in to see if there is any progress on this?
Hope you are doing well. Thanks.

**Comment by saravanan30erd** [comment]
@peterzhuamazon  sure, I recently added few more plugins in opendistro repo which I will test it and merge to master today. I will also start the work for opensearch after that.

**Comment by peterzhuamazon** [comment]
Thanks @saratvemulapalli that sounds great, let us know if you need any help.

cc: @bbarani

**Comment by saravanan30erd** [comment]
@peterzhuamazon

I have split the task into many phases, currently I have completed the single node opensearch setup.

I will work on below tasks in upcoming days,

- opensearch multi-node cluster setup
- opensearch dashbaords Installation
- Performance analyzer plugin configuration

please check it.

**Comment by peterzhuamazon** [comment]
Thanks @saravanan30erd for the 1st PR, will involve folks to review this one.
Thanks.

**Comment by prudhvigodithi** [comment]
OpenSearch ansible-playbook repo is up with ansible playbooks for both OS and OSD.
https://github.com/opensearch-project/ansible-playbook
Closing this issue, please re-open if required.
Thank you
