### ISSUE TITLE
OpenSearch Slack Community?

### ISSUE THREAD

**Issue by DandyDeveloper** [opensearch-project/opensearch-devops#15]
I know we have the OpenSearch community on Discuss but having some mechanism to interact with engineers actively supporting OpenSearch would be super helpful to me as a contributor. 

CNCF and others have Slack workspaces and numerous channels where people can interact. 

Although some of this information can get lost, Discuss isn't good enough and also is very hard to get responses on from time to time 

@peterzhuamazon  @TheAlgo What do you think?

**Comment by TheAlgo** [comment]
@stockholmux opinion?

**Comment by stockholmux** [comment]
Good call out but no plans currently for a Slack community. 

We've looked at a few separate times and there is even an [unofficial odfe/opensearch slack](odfe-workspace.slack.com), but we'd rather have one communications channel at the moment and that's [the forums](https://discuss.opendistrocommunity.dev/). It's more searchable, asynchronous (better for different time zones) and easier to manage from a code-of-conduct perspective.

**Comment by DandyDeveloper** [comment]
That sucks. I'll stick with the forums for now then.

**Comment by jkowall** [comment]
https://odfe-workspace.slack.com/ is the URL for signing up to the Slack.

**Comment by dblock** [comment]
@nknize

**Comment by nknize** [comment]
Live today at: http://opensearch.slack.com/
