### ISSUE TITLE
Plan for migrating helm chart?

### ISSUE THREAD

**Issue by KlavsKlavsen** [opensearch-project/opensearch-devops#2]
Whats your plans for migrating the helm chart from opendistro-es ?
Or are there things about it you're unhappy with, so you'd rather "have something else" ?

Can I help - f.ex. by taking a stab at migrating helm chart and https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/693 ? or is opensearch a bit from "being ready for first runnable release" ?

**Comment by TheAlgo** [comment]
@bbarani I took a stab and was able to spin up OpenSearch cluster using the helm chart. The only issue I am facing is that the cluster is not going green. I will raise a PR of the chart I have created. We can take it forward from there.

**Comment by bbarani** [comment]
@KlavsKlavsen We have merged the initial version of Helm chart via this [PR](https://github.com/opensearch-project/opensearch-devops/pull/4). Please provide your feedback after trying it out. I am closing this issue now, feel free to re-open it if you have any further questions.
