### ISSUE TITLE
Unusual max_local_storage_nodes value

### ISSUE THREAD

**Issue by smlx** [opensearch-project/opensearch-devops#22]
https://github.com/opensearch-project/opensearch-devops/blob/a2a2d8be7438a8dc5cbb300a8530f85a3784fd20/Helm/opensearch/values.yaml#L67-L68

Should these lines be present in the default `values.yaml` of the opensearch chart? According to the [elastic documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#max-local-storage-nodes) setting this to >1 is not safe, and not sure if it makes sense in a kubernetes statefulset.

**Comment by TheAlgo** [comment]
@smlx The value is just a demo configuration as mentioned in the `values.yaml` and does not portray anything.

**Comment by smlx** [comment]
Ok, I'll send a PR to remove it then because as a demo setting it doesn't make sense for a cluster running as a kubernetes statefulset.
