### ISSUE TITLE
[BUG][Opensearch] duplicate persistence config / storageClass option

### ISSUE THREAD

**Issue by belfhi** [opensearch-project/opensearch-devops#32]
**Describe the bug**
The configuration of the statefulset's persistence is done in two 
places, in `.Values.persistence` and in `.Values.volumeClaimTemplate` and should be
done in a single place instead, as is done in most other Helm Charts.
This also allows a more obvious place to enter a value for the `storageClass` to be used for the PVC.

**To Reproduce**
1. Go to the values.yaml file and check both config options

**Expected behavior**
only one place for PVC config should exist.

**Component**
peristence

**Host/Environment (please complete the following information):**
 - Helm v3.5.3
 - Version 1.0.0 of the tChart

**Comment by DandyDeveloper** [comment]
@TheAlgo Didn't I mention this in the review for the original PR adding OpenSearch?

Did we not manage to get it in?

**Comment by TheAlgo** [comment]
> @TheAlgo Didn't I mention this in the review for the original PR adding OpenSearch?
> 
> Did we not manage to get it in?

I remember you mentioning this in the initial PR. I did the changes as well. Looks like it got missed somewhere 😢
