### ISSUE TITLE
[BUG][opensearch] Missing volumes for securityConfig secrets

### ISSUE THREAD

**Issue by hgoscenski-imanage** [opensearch-project/opensearch-devops#42]
**Describe the bug**
Helm chart does not create volumes for the securityConfig secrets

**To Reproduce**
1. Utilize secrets for securityConfig

**Expected behavior**
Volumes provisioned such that the pod can start.

**Component**
Helm v3.6.x

**Screenshots**
NA

**Host/Environment (please complete the following information):**
 - Helm v3.6.x

**Additional context**
I will create a PR.

**Comment by hgoscenski-imanage** [comment]
Covered in PR #31

**Comment by TheAlgo** [comment]
@hgoscenski-imanage  As it is a duplicate of #26 , can we close it?

**Comment by hgoscenski-imanage** [comment]
@TheAlgo Absolutely.
