### ISSUE TITLE
provide helm chart

### ISSUE THREAD

**Issue by Hokwang** [opensearch-project/opensearch-devops#5]
Hello,

Like opendistro's helm chart,
will you have a plan for providing helm chart for opensearch?

Is this in your roadmap?

Thanks,

**Comment by peterzhuamazon** [comment]
Also, transfer the issue to the corresponding repo. Thanks.

**Comment by Hokwang** [comment]
@peterzhuamazon thanks!!! I will look around that PR.

**Comment by bbarani** [comment]
@Hokwang We have merged the initial version of Helm chart [PR](https://github.com/opensearch-project/opensearch-devops/pull/4). Please try using it and provide your feedback.
