### ISSUE TITLE
[Enhancement][opensearch-dashboards] support current ingress apiVersion

### ISSUE THREAD

**Issue by paltryeffort** [opensearch-project/opensearch-devops#50]
The ingress `apiVersion: networking.k8s.io/v1` is available in kubernetes since 1.19 and is the only valid version in kubernetes 1.22+.
1.22 was released in August 4th, 2021. Details: [api removals](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes)

**Comment by peterzhuamazon** [comment]
Thanks @paltryeffort.

@TheAlgo @DandyDeveloper @smlx is this something we need to worry about and take actions?

**Comment by peterzhuamazon** [comment]
nvm it has a PR already just need to link it #47
