### ISSUE TITLE
[Complete][Help Needed][Helm] Migrate Helm-Charts to opensearch-project/helm-charts Standalone Repo

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-devops#53]
**Is your feature request related to a problem? Please describe.**
We have published Helm-Charts standalone repo today with the help of community votes on naming #49.
https://github.com/opensearch-project/helm-charts

We now need to migrate helm charts from this repo to the standalone one.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheAlgo** [comment]
Hi All,

I have started the migration activity, will soon be able to raise the PR comprising both the charts in the new repository.

**Comment by peterzhuamazon** [comment]
@TheAlgo draft PR: https://github.com/opensearch-project/helm-charts/pull/7

**Comment by peterzhuamazon** [comment]
Close this issue as the initial migration efforts is complete.
