### ISSUE TITLE
[BUG][securityConfig labels using wrong expression]

### ISSUE THREAD

**Issue by NagleZhang** [opensearch-project/opensearch-devops#62]
**Describe the bug**
if we are using securityConfig. we got below error.

Error: UPGRADE FAILED: YAML parse error on opensearch/templates/securityconfig.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Chart.Name":interface {}(nil)} 

**To Reproduce**
1. add values for `securityConfig.config.SecurityConfigSecret` & `securityConfig.config.data`
2. upgrade helm
3. got failed message: `Error: UPGRADE FAILED: YAML parse error on opensearch/templates/securityconfig.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Chart.Name":interface {}(nil)} ` 

**Expected behavior**
able to add security config. 

**Component**
HELM

**Screenshots**

WSL2 Ubuntu VERSION="18.04.4 LTS (Bionic Beaver)"

**Additional context**
None

**Comment by TheAlgo** [comment]
Closing in favour of this [PR](https://github.com/opensearch-project/helm-charts/pull/7)
