### ISSUE TITLE
[Migration][Helm] Cleanup the helm folders in devops repo and add pointers to helm-charts repo

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-devops#66]
**Is your feature request related to a problem? Please describe.**
Cleanup the helm folders in devops repo and add pointers to helm-charts repo
https://github.com/opensearch-project/helm-charts

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheAlgo** [comment]
I can take this up and clean this repo. Will raise a PR soon.
