### ISSUE TITLE
[Enhancement][Prometheus-Metrics]How to enable prometheus-metrics plugin

### ISSUE THREAD

**Issue by alochym01** [opensearch-project/opensearch-devops#68]
How do i enable plugin
https://github.com/aparo/opensearch-prometheus-exporter

thank you

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo @smlx any comments on this one? Thanks.

**Comment by alochym01** [comment]
hi, any news update :)

**Comment by DandyDeveloper** [comment]
I'll spend some time on this Monday or Tuesday JST.

I'll have more information then. Please assign to me.

**Comment by DandyDeveloper** [comment]
I've made a new issue in the official charts repo: https://github.com/opensearch-project/helm-charts/issues/50

**Comment by peterzhuamazon** [comment]
Close this issue as it is duplicated to opensearch-project/helm-charts#50, please use that one to track progress.
Thanks.
