### ISSUE TITLE
Plans for an Officially Recognized Terraform Provider

### ISSUE THREAD

**Issue by jackson-theisen** [opensearch-project/opensearch-devops#82]
### Is your feature request related to a problem? Please describe

Currently, the best Terraform provider that exists for managing OpenSearch components such as index templates, ISM policies, etc, is a community-managed repository: https://github.com/phillbaker/terraform-provider-elasticsearch. Unless there are plans to develop a completely separate Terraform provider to accomplish similar tasks, it seems worthwhile to me to get that repo imported to the https://github.com/opensearch-project organization. 

### Describe the solution you'd like

Migrate https://github.com/phillbaker/terraform-provider-elasticsearch into the https://github.com/opensearch-project organization. Ensure that @phillbaker is given all the credit he deserves somewhere at the top of the README. Then submit the provider to the [Terraform Integration Program](https://www.terraform.io/docs/partnerships#terraform-integration-program) to get a nice shiny "Verified" badge in the provider registry. 

References:
- https://www.terraform.io/registry/providers#provider-tiers-namespaces
- https://www.terraform.io/docs/partnerships
- https://github.com/phillbaker/terraform-provider-elasticsearch

### Additional context

I have also opened an issue to take @phillbaker's temperature around getting this done: https://github.com/phillbaker/terraform-provider-elasticsearch/issues/299. Apologies in advance if this isn't the right place to discuss this matter, but it seemed fitting enough.

**Comment by elfisher** [comment]
@jackson-theisen are you interested in helping maintain this repo if it is transferred to the OpenSearch Project?

**Comment by jackson-theisen** [comment]
@elfisher I'd be more than happy to help maintain the repo, but would like @phillbaker to be the primary admin as he is the original author. Based on his response to my issue in his repository, sounds like he'd be open to it as long as I did the heavy lifting around the migration. See https://github.com/phillbaker/terraform-provider-elasticsearch/issues/299#issuecomment-1203407963 for reference.

**Comment by bbarani** [comment]
Closing this issue as we have created https://github.com/opensearch-project/terraform-provider-opensearch repo within OpenSearch org now.
