### ISSUE TITLE
Opensearch 2.1.1 restarts 5 times under Docker Swarm

### ISSUE THREAD

**Issue by electricbrain-code** [opensearch-project/opensearch-devops#84]
Getting this 5 times (i.e. container finishes then Portainer restarts it). On the 5th time it just runs?
Is this expected ?
Cheers and thanks in advance for any help (although everything is working well so far - apart from this issue).
The security is indeed configured (as reported) and uses LDAP as well as inbuilt security.

Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
OpenSearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/opensearch
OpenSearch install type: rpm/deb on NAME="Amazon Linux"
OpenSearch config dir: /usr/share/opensearch/config
OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin
OpenSearch plugins dir: /usr/share/opensearch/plugins
OpenSearch lib dir: /usr/share/opensearch/lib
Detected OpenSearch Version: x-content-2.1.1
Detected OpenSearch Security Version: 2.1.1.0
/usr/share/opensearch/config/opensearch.yml seems to be already configured for Security. Quit.
Enabling OpenSearch Security Plugin
Killing opensearch process 33
OpenSearch exited with code 143
Performance analyzer exited with code 127

**Comment by prudhvigodithi** [comment]
Hey @electricbrain-code can you please share the full installation setup, how are you trying to configure the cluster via helm?
I see from the error `opensearch.yml` is already added to the security index, looks like its reloading every time with your setup, can you add some more details please?

**Comment by electricbrain-code** [comment]
Hi Prudhvi,
Thanks for looking at this. Not Helm, this is Portainer from [@portainer.io](https://github.com/portainer).
There have been a number of upgrades now to both Portainer (currently running 2.15.1) and OpenSearch (currently running v2.3.0).
There were no issues at all running up OpenSearch 2.3.0. Everything is just working fine now.
Probably need to close this issue.

What follows is the Portainer template used to start the stack (as requested):
version: '3.7'
services:
  opensearch-2-2-1-node1:
    image: registry:5000/opensearchproject/opensearch:2.2.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.platform.arch==aarch64"
          - "node.hostname==hostc.localdomain"
      resources:
        limits:
          cpus: '4.00'
          memory: 6G
        reservations:
          cpus: '2.00'
          memory: 4G
    environment:
      cluster.name:                        opensearch-2-2-1-cluster
      node.name:                           opensearch-2-2-1-node1
      discovery.seed_hosts:                opensearch-2-2-1-node1
      OPENSEARCH_JAVA_OPTS:              "-Xms3072m -Xmx3072m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      bootstrap.memory_lock:              "true"
      discovery.type:                     "single-node"
      HTTP_PUBLISH_HOST:                  "0.0.0.0"
      HTTP_PUBLISH_PORT:                   9200
      TRANSPORT_PUBLISH_HOST:             "opensearch-2-2-1-node1"
      TRANSPORT_PUBLISH_PORT:              9300
#     DISABLE_SECURITY_PLUGIN:            "true"              # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      path.repo:                          "/snapshots"
#     - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - /docker.local/opensearch-2-2-1/data/usr/share/opensearch/config:/usr/share/opensearch/config
      - /docker.local/opensearch-2-2-1/data/usr/share/opensearch/data:/usr/share/opensearch/data
      - /docker.local/opensearch-2-2-1/data/usr/share/opensearch/plugins/opensearch-security/securityconfig:/usr/share/opensearch/plugins/opensearch-security/securityconfig
      - /jbod-disk0/snapshot/opensearch_2.2.1_backups:/snapshots
    ports:
      - target:    9200
        published: 9200
        protocol:  tcp
#     - target:    9300
#       published: 9300
#       protocol:  tcp
      - target:    9600 # required for Performance Analyzer
        published: 9600
        protocol:  tcp
    networks:
      - opensearch-2-2-1-net


  opensearch-2-2-0-dashboards:
    image: registry:5000/opensearchproject/opensearch-dashboards:2.2.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - "node.platform.arch==aarch64"
          - "node.labels.system==RPi4"
          - "node.labels.public==true"
      resources:
        limits:
          cpus: '2.00'
          memory: 1G
        reservations:
          cpus: '1.00'
          memory: 512M
    ports:
      - target:    5601
        published: 8602
        protocol:  tcp
    environment:
      OPENSEARCH_HOSTS:                   '["https://opensearch-2-2-1-node1:9200"]'
#     DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"               # disables security dashboards plugin in OpenSearch Dashboards
    networks:
      - opensearch-2-2-1-net

**Comment by jordarlu** [comment]
Thanks for letting us know, @electricbrain-code , I am closing this issue now, and pls feel free to open/re-open it if any concern, thanks again!
