### ISSUE TITLE
[BUG] OpenSearch Docker Container

### ISSUE THREAD

**Issue by liamcassidy-eb** [opensearch-project/opensearch-devops#86]
**Describe the bug**
Hello, I'm running into an issue where I can't connect to the opensearch docker container following the opensearch documentation outlined here: 
https://opensearch.org/docs/latest/opensearch/install/docker/

**To Reproduce**
```
docker pull opensearchproject/opensearch:latest
docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:latest
```
In a separate terminal tab I run:
```
curl -XGET https://localhost:9200 -u admin:admin --insecure
```
I get the following response:
```
~ % curl -XGET https://localhost:9200 -u admin:admin --insecure
curl: (7) Failed to connect to localhost port 9200 after 8 ms: Connection refused
```

**Expected behavior**
I expect the curl GET request to connect

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Mac OS Monterey
 - Version 12.4

**Additional context**
I'm running docker via [Colima](https://github.com/abiosoft/colima) installed via homebrew
```
~ % colima status   
INFO[0000] colima is running                            
INFO[0000] arch: x86_64                                 
INFO[0000] runtime: docker                              
INFO[0000] mountType:                                   
INFO[0000] socket: unix:///Users/<my username>/.colima/default/docker.sock 
```

Thanks in advance! 🙏

**Comment by dblock** [comment]
Moved this to opensearch-devops.

**Comment by prudhvigodithi** [comment]
Hey @liamcassidy-eb running `docker run -it -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:2.2.0`  and once you are into (exec) the container, the following command should work, please check the logs until the OpenSearch is full up and running.
```
curl -XGET https://localhost:9200 -u admin:admin --insecure
{
  "name" : "69c22a212027",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "hpFTibawRnCWbOPIOSwgtg",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.2.0",
    "build_type" : "tar",
    "build_hash" : "b1017fa3b9a1c781d4f34ecee411e0cdf930a515",
    "build_date" : "2022-08-09T02:27:25.256769336Z",
    "build_snapshot" : false,
    "lucene_version" : "9.3.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

Thank you

**Comment by prudhvigodithi** [comment]
Hey @liamcassidy-eb I suspect this is something to do with colima setup.
