### ISSUE TITLE
[BUG] OpenSearch docker images can't running on the ARM machine

### ISSUE THREAD

**Issue by loxiaopohaiol** [opensearch-project/opensearch-devops#87]
I use the command “docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:2.2.0” to start a test opensearch which running by docker, but it can't running. The container log is below:
![image](https://user-images.githubusercontent.com/48348273/185598547-93403661-b4c5-484b-99ac-e929cb7253b2.png)

**Comment by dblock** [comment]
Moving this to opensearch-devops.

**Comment by prudhvigodithi** [comment]
Hey @loxiaopohaiol I have tested on ane arm64 ec2 instance `docker run -it -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:2.2.0`

[ARM64 tag](https://hub.docker.com/layers/opensearchproject/opensearch/2.2.0/images/sha256-397fec74387a7437871f0371dda7f4ec6cc5f2edd64f861096010c7c372dc7b4?context=explore)

```
docker inspect opensearchproject/opensearch:2.2.0 | grep -i Architecture
        "Architecture": "arm64",
```
```
opensearch@bd006c139491 ~]$ uname -a
Linux bd006c139491 5.10.135-122.509.amzn2.aarch64 #1 SMP Thu Aug 11 22:41:14 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
[opensearch@bd006c139491 ~]$ curl -XGET https://localhost:9200 -u admin:admin --insecure
{
  "name" : "bd006c139491",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "hzKJYNl-SkWchAIWlHvLJQ",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.2.0",
    "build_type" : "tar",
    "build_hash" : "b1017fa3b9a1c781d4f34ecee411e0cdf930a515",
    "build_date" : "2022-08-09T02:28:05.169390805Z",
    "build_snapshot" : false,
    "lucene_version" : "9.3.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**Comment by prudhvigodithi** [comment]
Hey @loxiaopohaiol can you please post an update, if you had any issues from your arm server?
@bbarani @peterzhuamazon

**Comment by loxiaopohaiol** [comment]
My vm OS is 'Kylin Linux Advanced Server release V10', the docker server version is 19.03.15, and the CPU is ARM. When I run the opensearch by docker(the commond is "docker run -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:latest"), the log show that:
image

after that the container not running.
And then I change the docker entrypint file (opensearch-docker-entrypoint.sh) line 105(trap terminateProcesses TERM INT EXIT CHLD) to (trap terminateProcesses TERM INT EXIT), and the container can runing normal，So why the container can't running which use the offical image on this environment?

**Comment by loxiaopohaiol** [comment]
@prudhvigodithi According to the offical images' file(opensearch-docker-entrypoint.sh), has the CHLD explanation:
![image](https://user-images.githubusercontent.com/48348273/197747563-5e450ad0-9c21-479a-9bf6-f84a1c020bd6.png)
and how can I search which processes has terminated? I can't see any error log in my contianer.

**Comment by jordarlu** [comment]
Hello, @loxiaopohaiol , sorry to get back to you late but I want to follow up on this issue and see how we can move forward on it. 

There was another case fail the OpenSearch cluster and then, the team took an action to remove Performance Analyzer (short for PA) dependancy. Please refer to https://github.com/opensearch-project/opensearch-build/pull/2876 for detail.
With that, I wonder if you could give it a try with Opensesarch v2.5.0 or later if you haven't yet?  

There is a runOpensearch function in opensearch-docker-entrypoint.sh that is designed to Exit if either Openseatch or PA fail/halts for any reasons. With the PA decoupling, I hope you can get the cluster up and running on your Kylin Linux ( sorry that I don't have any experience on Kylin Linux but I assume you would have done all the necessary configurations to make the docker working including some network settings, and possibly adding user accounts to the Docker group?)

**Comment by jordarlu** [comment]
Hello, @loxiaopohaiol , since this issue has been opened for quite some time, I am closing this issue for now, and please open a new issue/re-open it if you are still facing difficulties .. thank you!
