### ISSUE TITLE
[BUG] Windows Docker Desktop

### ISSUE THREAD

**Issue by Yafaa** [opensearch-project/opensearch-devops#88]
**Describe the bug**
I am using Docker desktop with windows and tried to run opensearch via  docker-compose up
but I am getting this error from the logs
`opensearch-dashboards    | {"type":"log","@timestamp":"2022-08-19T17:14:40Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: getaddrinfo ENOTFOUND opensearch-node1"}`

My docker desktop said to use WSL2 backend so I created .wslconfig in my %UserProfile% folder
And I Added this 
[wsl2]
memory=4GB   # Limits VM memory in WSL 2 up to 4GB
but still same issue

**Host/Environment (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by prudhvigodithi** [comment]
Hey @Yafaa can you please try to query the OpenSearch node from Dashboard container, something like `curl -XGET https://<os_container_ip>:9200 -u admin:admin --insecure`, if still dint work can you the try the following 
```
For OpenSearch
ports:
- 127.0.0.1:9200:9200
- 127.0.0.1:9600:9600

For OpenSearch Dashboards:
ports:
- 127.0.0.1:5601:5601
```

**Comment by prudhvigodithi** [comment]
Hey @Yafaa can you please post an update if you have tried with the suggestion[ posted above ](https://github.com/opensearch-project/opensearch-devops/issues/88#issuecomment-1230951685) ;)

**Comment by jordarlu** [comment]
Hello, @Yafaa , I just want to follow up on this case, and see if you still need any help from the team here ,,, since you posted the error said 'ConnectionError', we would first want to know if the Opensearch cluster ended up with those default ports (9200, 9600) opened or failed. If you could please give it a try as @prudhvigodithi mentioned above (on Aug 29, 2022).

**Comment by jordarlu** [comment]
Hello @Yafaa, since this issue has been opened for quite sometime, I am closing this issue for now, and please open a new issue/re-open it if you are still facing difficulties .. thank you!
