### ISSUE TITLE
Cannot connect to Opensearch dashboard

### ISSUE THREAD

**Issue by VartikaSharma14** [opensearch-project/opensearch-devops#95]
I am using OpenSearch with docker compose file.
Both services (5601 & 9200) are working fine. 

But when I try to  add volume in OpenSearch-dashboard service, dashboard is not reachable.
<img width="723" alt="image" src="https://user-images.githubusercontent.com/99406269/204262269-a6001e2d-339a-4d6c-8ef1-a14e33984566.png">

Can please anyone help!

**Comment by gaiksaya** [comment]
[Triage] Hey @VartikaSharma14 ,

Can you take a look at the docker-compose from our website https://opensearch.org/samples/docker-compose.yml for reference? If it still does not work can you post your docker-compose file here so that we can take a look?
Thanks!

**Comment by jordarlu** [comment]
Hello, @VartikaSharma14, I am closing this issue for now, and please open a new issue/re-open it if you are still facing difficulties .. thank you!
