### ISSUE TITLE
Permission denied - /usr/share/opensearch/

### ISSUE THREAD

**Issue by lindeberg25** [opensearch-project/opensearch-devops#97]
Hello...

I'm deploying an opensearch cluster on Openshift and I'm getting the permission denied error: ./opensearch-docker-entrypoint.sh: permission denied"

I've created an opensearch-sa service account and added it to master.yaml:

         serviceAccountName: "opensearch-sa"

I've set opensearch-sa to privileged.

I believe the user created in the opensearch image doesn't have permission on /usr/share/opensearch/opensearch-docker-entrypoint.sh, which is a little weird. (I think the image user should already have permission to access that folder)

Could someone tell me what I'm missing?

Thanks in advance

**Comment by IAMohamed** [comment]
Had the same issue. Fix: at the container level, define the securityContext of runAsUser and runAsGroup to:     
 securityContext:
        runAsUser: 1000
        runAsGroup: 1000

**Comment by peterzhuamazon** [comment]
Echo @Ismo900123213, In our docker the user we user to run is having 1000 id.
And the default user should be them as well.

If you are having another user trying to access the folder then it will error out. Thanks.

**Comment by midprasanta** [comment]
Is there any plan to fix the issue. Error happens in openshift only.
